portfolio_performance:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "portfolio.duckdb"
      threads: 4

    prod:
      type: duckdb
      path: "portfolio_prod.duckdb"
      threads: 4